[package]
name = "slow5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
cstr = "0.2.10"
slow5lib-sys = { version = "0.1.0", path="slow5lib-sys" }
thiserror = "1.0.30"

[dev-dependencies]
anyhow = "1.0.56"
