[package]
name = "slow5"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"
readme = "README.md"
authors = ["Brandon Saint-John <bsaintjo@ucsc.edu>"]
repository = "https://github.com/bsaintjo/slow5-rs"
homepage = "https://github.com/hasindu2008/slow5lib"
description = "Library for interacting with slow5"
documentation = "https://doc.rs/slow5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
cstr = "0.2.10"
slow5lib-sys = { version = "0.1.0", path="slow5lib-sys" }
thiserror = "1.0.30"

[dev-dependencies]
anyhow = "1.0.56"
