[package]
name = "parallel-read"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
rayon = "1.6.1"
slow5 = { version = "0.12.0", path = "../../" }
