name: coverage

on:
  push:
    branches: [ main ]
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "tarpaulin.toml"
  pull_request:
    branches: [ main ]
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "tarpaulin.toml"
  workflow_dispatch:
    

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2

      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Generate code coverage
        run: cargo tarpaulin --out Xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{secrets.CODECOV_TOKEN}}
