name: Rust

on:
  push:
    branches: [ main ]
    paths:
      - "**.rs"
      - "Cargo.toml"
  pull_request:
    branches: [ main ]
    paths:
      - "**.rs"
      - "Cargo.toml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run tests
      run: cargo test --workspace --verbose && cargo test --examples
