name: Rust

on:
  push:
    branches: [ main ]
    paths:
      - "**.rs"
      - "Cargo.toml"
  pull_request:
    branches: [ main ]
    paths:
      - "**.rs"
      - "Cargo.toml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: [--all-features, --no-default-features]
        toolchain: [stable, nightly]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install toolchain
      uses: dtolnay/rust-toolchain@${{ matrix.toolchain }}

    - name: Check cache
      uses: Swatinem/rust-cache@v2

    - name: Run tests
      run: cargo test --workspace --verbose ${{ matrix.features }}

    - name: Run examples
      run: cargo test --examples --verbose ${{ matrix.features }}
